/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.Produtos;

import SistemaZika.Aplicacao;
import SistemaZika.DAO.ProdutoDAO;
import SistemaZika.Mascara;
import SistemaZika.Models.ProdutoModel;
import SistemaZika.SearchJTable;
import exemplo.Pages.Fornecedores.AddFornecedor;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Nunes
 */
public class Produtos extends javax.swing.JPanel {

    /**
     * Creates new form Produtos
     */
    public ArrayList<ProdutoModel> Produtos;
    public ProdutoDAO PDAO;
    public Produtos() {
        initComponents();
        jFormattedTextFieldData.setFormatterFactory(Mascara.setMaskData());
        PDAO= new ProdutoDAO();
        Produtos = PDAO.SelecionaTudo();
        
        //jTableProdutos
        String[] Colunas = {"id_produto","nome","status","unidade"};
        DefaultTableModel TableModel = new DefaultTableModel (null,Colunas);
                
        for (int i=0; i<Produtos.size(); i++){
            ProdutoModel TempProduto = (ProdutoModel) Produtos.get(i);
            Object [] Linhas = {TempProduto.getId_produto(),TempProduto.getNome(),TempProduto.getStatus(),TempProduto.getUnidade()};
            TableModel.addRow(Linhas);
            
        }
            jTableProdutos.setModel(TableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldSearch = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jButtonEditar = new javax.swing.JButton();
        jButtonAtualizarTAB = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Pages/Produtos/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("Produtos.jLabel1.text")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextFieldSearch.setText(bundle.getString("Produtos.jTextFieldSearch.text")); // NOI18N
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });
        add(jTextFieldSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 87, -1));

        jButton5.setText(bundle.getString("Produtos.jButton5.text")); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidade", "Caixa", "Litro", "Quilos" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 65, -1));

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProdutos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 720, -1));

        jFormattedTextFieldData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldDataKeyTyped(evt);
            }
        });
        add(jFormattedTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 65, -1));

        jButtonEditar.setText(bundle.getString("Produtos.jButtonEditar.text")); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jButtonAtualizarTAB.setText(bundle.getString("Produtos.jButtonAtualizarTAB.text")); // NOI18N
        jButtonAtualizarTAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTABActionPerformed(evt);
            }
        });
        add(jButtonAtualizarTAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFrame addProduto = new AddProdutos();
        addProduto.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here
        int linha = jTableProdutos.getSelectedRow();
        if (linha != -1){
            Object idProduto = jTableProdutos.getValueAt(linha, 0);
            if(Integer.parseInt(idProduto.toString())!= -1){
               AddProdutos verProduto = new AddProdutos(idProduto.toString());
               verProduto.setVisible(true);
            }
        }else{
        JOptionPane.showMessageDialog(null, "Selecione a linha que deseja editar");}
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonAtualizarTABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTABActionPerformed
        // TODO add your handling code here:
        //Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel AtualizaNF = new Produtos();
        Aplicacao.Corpo.add(AtualizaNF, BorderLayout.CENTER);
        jTextFieldSearch.requestFocus();
    }//GEN-LAST:event_jButtonAtualizarTABActionPerformed

    private void jFormattedTextFieldDataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataKeyTyped
        // TODO add your handling code here:
        SearchJTable.SearchJTable(jTableProdutos, jTextFieldSearch);
    }//GEN-LAST:event_jFormattedTextFieldDataKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAtualizarTAB;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
