/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.Fornecedores;

import SistemaZika.DAO.FornecedoreDAO;
import SistemaZika.DAO.SqlConecta;
import SistemaZika.Eventos;
import SistemaZika.LimitaQtdaCaracteres;
import SistemaZika.Mascara;
import SistemaZika.Models.FornecedorModel;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Leonardo Nunes
 */
public class AddFornecedor extends javax.swing.JFrame {

    SqlConecta conecta = new SqlConecta();
    private FornecedorModel fornecedor;
    private FornecedoreDAO pdao;
    /**
     * Creates new form AddFornecedor
     */
    public JFrame Self;
    
    public AddFornecedor(){
        initPage();
        jButtonEditar.setVisible(false);
        
    }
    public AddFornecedor(String id_produto){
        initPage();
        jButton1.setVisible(false);
         pdao = new FornecedoreDAO();
         fornecedor = pdao.SelecionaPorID(id_produto);
        jTextFieldNomeF.setText(fornecedor.getNome());
        jFormattedTextFieldCNPJ.setText(fornecedor.getCnpj());
        jFormattedTextFieldTelefone.setText(fornecedor.getTelefone());
        jComboBoxStatusF.setSelectedItem(fornecedor.getStatus());
    }
    
    public void initPage() {
        initComponents();
        jFormattedTextFieldCNPJ.setFormatterFactory(Mascara.setMaskCNPJ());
        jFormattedTextFieldTelefone.setFormatterFactory(Mascara.setMaskTelFixo());
        this.Self = this;
        Eventos.setAcessibilidade(this);
        jTextFieldNomeF.requestFocus();

        this.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                //Verificando se o botão direito do mouse foi clicado
                if ((me.getModifiers() & MouseEvent.BUTTON3_MASK) != 0) {
                    JPopupMenu menu = new JPopupMenu();
                    JMenuItem item = new JMenuItem("Clique-me");
                    menu.add(item);
                    JMenuItem item2 = new JMenuItem("Salvar");
                    menu.add(item2);

                    item.addActionListener(new ActionListener() {
                        public void actionPerformed(ActionEvent ae) {
                            JOptionPane.showMessageDialog(null, "Fui clicado !");
                        }
                    });

                    menu.show(Self, me.getX(), me.getY());
                }
            }
        });
        jTextFieldNomeF.setDocument(new LimitaQtdaCaracteres(254));
        Eventos.mudacorfoco(jTextFieldNomeF);
        Eventos.mudacorfoco(jFormattedTextFieldTelefone);
        Eventos.mudacorfoco(jFormattedTextFieldCNPJ);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAddF = new javax.swing.JLabel();
        jTextFieldNomeF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jComboBoxStatusF = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAddF.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Pages/Fornecedores/Bundle"); // NOI18N
        jLabelAddF.setText(bundle.getString("AddFornecedor.jLabelAddF.text")); // NOI18N
        getContentPane().add(jLabelAddF, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 39, 173, -1));

        jTextFieldNomeF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNomeFKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNomeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 103, 234, -1));

        jLabel2.setText(bundle.getString("AddFornecedor.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 83, 38, -1));

        jLabel3.setText(bundle.getString("AddFornecedor.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 141, -1, -1));

        jLabel4.setText(bundle.getString("AddFornecedor.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 199, -1, -1));

        jButton1.setText(bundle.getString("AddFornecedor.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jFormattedTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCNPJActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 168, 234, -1));

        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 224, 234, -1));

        jComboBoxStatusF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inativo\t", "Ativo" }));
        getContentPane().add(jComboBoxStatusF, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 277, 125, -1));

        jLabel1.setText(bundle.getString("AddFornecedor.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 260, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText(bundle.getString("AddFornecedor.jLabel5.text")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 106, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText(bundle.getString("AddFornecedor.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 171, -1, -1));

        jButtonEditar.setText(bundle.getString("AddFornecedor.jButtonEditar.text")); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 77, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         TODO add your handling code here:
//
//        Color danger = new Color(214, 135, 135);
//        Color success = new Color(135, 214, 137);
//
//        if (jTextFieldNomeF.getText().replace("_", "").replace("/", "").trim().length() > 0 && jTextFieldNomeF.getText().length() <= 10) {
//            jTextFieldNomeF.setBackground(success);
//        } else {
//            jTextFieldNomeF.setBackground(danger);
//        if (setBackground(success)){
            if (jTextFieldNomeF.getText().equals("")){
                jTextFieldNomeF.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo Nome é obrigatório","Aviso",JOptionPane.WARNING_MESSAGE);
                return;
            }   
                if (jFormattedTextFieldCNPJ.getText().equals("________/__")){
                jFormattedTextFieldCNPJ.requestFocus();
                JOptionPane.showMessageDialog(null, "O campo CNPJ é obrigatório","Aviso",JOptionPane.WARNING_MESSAGE);
                return;
            }
            try {
                PreparedStatement pst = conecta.getConnection().prepareStatement("insert into Fornecedores(nome,cnpj,telefone,status)values(?,?,?,?)");
                pst.setString(1, jTextFieldNomeF.getText().replace("_", "").replace("/", "").trim());
                pst.setString(2, jFormattedTextFieldCNPJ.getText().replace("_", "").replace("/", "").trim());
                pst.setString(3, jFormattedTextFieldTelefone.getText().replace("_", "").replace("(", "").replace("-", "").replace(")", "").trim());
                pst.setInt(4, jComboBoxStatusF.getSelectedIndex());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro na inserção! \n ERRO:!" + ex + "  chame o tecnico!!");;
            }
              this.setVisible(false);
//            jTextFieldNomeF.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jFormattedTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCNPJActionPerformed

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        
        fornecedor.setNome(jTextFieldNomeF.getText());
        fornecedor.setCnpj(jFormattedTextFieldCNPJ.getText().replace("_", "").replace("/", "").trim());
        fornecedor.setTelefone(jFormattedTextFieldTelefone.getText().replace("_", "").replace("(", "").replace("-", "").replace(")", "").trim());
        fornecedor.setStatus(jComboBoxStatusF.getSelectedIndex());
        
        pdao.Editar(fornecedor);
        JOptionPane.showMessageDialog(null, "Editado com Sucesso");
        this.setVisible(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxStatusF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAddF;
    private javax.swing.JTextField jTextFieldNomeF;
    // End of variables declaration//GEN-END:variables
}
