/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.Fornecedores;

import SistemaZika.Aplicacao;
import SistemaZika.DAO.FornecedoreDAO;
import SistemaZika.Models.FornecedorModel;
import SistemaZika.SearchJTable;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Nunes
 */
public class Fornecedores extends javax.swing.JPanel {

    /**
     * Creates new form Fornecedores
     */
     public ArrayList<FornecedorModel> Fornecedores;
     public ArrayList<FornecedorModel> FornecedoresIna;
    public FornecedoreDAO FDAO;
    public Fornecedores() {
        initComponents();
        //jScrollPane1.setVisible(false);
        
        FDAO= new FornecedoreDAO();
        Fornecedores = FDAO.SelecionaTudo();
        
        //jTableProdutos
        String[] Colunas = {"id_fornecedor","nome","cnpj","telefone","status"};
        DefaultTableModel TableModel = new DefaultTableModel (null,Colunas);
                
        for (int i=0; i<Fornecedores.size(); i++){
            FornecedorModel TempFornecedores = (FornecedorModel) Fornecedores.get(i);
            Object [] Linhas = {TempFornecedores.getId_fornecedor(),TempFornecedores.getNome(),TempFornecedores.getCnpj(),TempFornecedores.getTelefone(),TempFornecedores.getStatus()};
            TableModel.addRow(Linhas);
            
        }
            jTableFornecedores.setModel(TableModel);
            
            
//tabela inativos
//            FDAO= new FornecedoreDAO();
//            FornecedoresIna = FDAO.SelecionaTudoInativos();
//            
//            
//            String[] Colunas2 = {"id_fornecedor","nome","cnpj","telefone","status"};
//        DefaultTableModel TableModel2 = new DefaultTableModel (null,Colunas);
//                
//        for (int i=0; i<FornecedoresIna.size(); i++){
//            FornecedorModel TempFornecedoresIna = (FornecedorModel) FornecedoresIna.get(i);
//            Object [] Linhas = {TempFornecedoresIna.getId_fornecedor(),TempFornecedoresIna.getNome(),TempFornecedoresIna.getCnpj(),TempFornecedoresIna.getTelefone(),TempFornecedoresIna.getStatus()};
//            TableModel2.addRow(Linhas);}
//            jTableInativos.setModel(TableModel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddFornecedor = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFornecedores = new javax.swing.JTable();
        jButtonEditarF = new javax.swing.JButton();
        jButtonAtualizarTa = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Pages/Fornecedores/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("Fornecedores.jLabel1.text")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnAddFornecedor.setText(bundle.getString("Fornecedores.btnAddFornecedor.text")); // NOI18N
        btnAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFornecedorActionPerformed(evt);
            }
        });
        add(btnAddFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyTyped(evt);
            }
        });
        add(jTextFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 82, -1));

        jTableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableFornecedores);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 730, 260));

        jButtonEditarF.setText(bundle.getString("Fornecedores.jButtonEditarF.text")); // NOI18N
        jButtonEditarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarFActionPerformed(evt);
            }
        });
        add(jButtonEditarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jButtonAtualizarTa.setText(bundle.getString("Fornecedores.jButtonAtualizarTa.text")); // NOI18N
        jButtonAtualizarTa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTaActionPerformed(evt);
            }
        });
        add(jButtonAtualizarTa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFornecedorActionPerformed
        // TODO add your handling code here:
        JFrame addFornecedor = new AddFornecedor();
        addFornecedor.setVisible(true);
    }//GEN-LAST:event_btnAddFornecedorActionPerformed

    private void jButtonEditarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarFActionPerformed
        // TODO add your handling code here:
        int linha = jTableFornecedores.getSelectedRow();
        if (linha != -1){
            Object idFornecedor = jTableFornecedores.getValueAt(linha, 0);
            if(Integer.parseInt(idFornecedor.toString())!= -1){
               AddFornecedor verProduto = new AddFornecedor(idFornecedor.toString());
               verProduto.setVisible(true);
            }
        }else{
        JOptionPane.showMessageDialog(null, "Selecione a linha que deseja editar");}
    }//GEN-LAST:event_jButtonEditarFActionPerformed

    private void jButtonAtualizarTaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTaActionPerformed
        // TODO add your handling code here:
        //Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel AtualizaForn = new Fornecedores();
        Aplicacao.Corpo.add(AtualizaForn, BorderLayout.CENTER);
        jTextFieldPesquisar.requestFocus();
    }//GEN-LAST:event_jButtonAtualizarTaActionPerformed

    private void jTextFieldPesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyTyped
        // TODO add your handling code here:
        SearchJTable.SearchJTable(jTableFornecedores, jTextFieldPesquisar);
    }//GEN-LAST:event_jTextFieldPesquisarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFornecedor;
    private javax.swing.JButton jButtonAtualizarTa;
    private javax.swing.JButton jButtonEditarF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFornecedores;
    public static javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
