/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.NotasFiscais;

import SistemaZika.DAO.FornecedoreDAO;
import SistemaZika.DAO.NFDAO;
import SistemaZika.DAO.Nf_ProdutosDAO;
import SistemaZika.DAO.SqlConecta;
import SistemaZika.Eventos;
import SistemaZika.FormataDecimalCampo;
import SistemaZika.LimitaQtdaCaracteres;
import SistemaZika.Mascara;
import SistemaZika.Models.FornecedorModel;
import SistemaZika.Models.ModelNF;
import SistemaZika.Models.Nf_produtosModel;
import com.mysql.jdbc.Statement;
import exemplo.Pages.Fornecedores.AddFornecedor;
import exemplo.Pages.Produtos.AddProdutos;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Nunes
 */
public class ADDNotasFiscais extends javax.swing.JFrame {

    /**
     * Creates new form ADDNotasFiscais
     */
    private ModelNF NF;
    private NFDAO nfdao;
    
    
    public static int idF;
     public static int idP;
     public int ultimoID = 0;
     public FornecedorModel forn = new FornecedorModel();
     public FornecedoreDAO fdao = new FornecedoreDAO();
     SqlConecta conecta = new SqlConecta();
    public ADDNotasFiscais() {
        InitPage();
        btnEditar.setVisible(false);
    }
    public ADDNotasFiscais(String idNota){
        InitPage();
        jButtonAdicionarNF.setVisible(false);
        nfdao = new NFDAO();
         NF = nfdao.SelecionaPorID(idNota);
         jTextFieldNumero.setText("" + NF.getNumero());
         jTextFieldNS.setText(""+ NF.getSerie());
        // jTextFieldNome.setText(""+ NF.get);
        jTextFieldValor.setText("" + NF.getValor());
       forn = fdao.SelecionaPorID("" + NF.getId_fornecedor());
       jTextFieldNome.setText (forn.getNome());
       jFormattedTextFieldCNPJ.setText(forn.getCnpj());
        ListarProdutos(Integer.parseInt(idNota));
    }    
    public void InitPage(){    
        initComponents();
        //btnNotasFiscais.setFocusable(false);
        jTextFieldNumero.setFocusable(true);
        //jTextFieldNF.setRequestFocusEnabled(true);
        jTextFieldNumero.requestFocus();
        jTextFieldValor.setDocument(new FormataDecimalCampo(10, 2));
        jTextFieldValorprod.setDocument(new FormataDecimalCampo(10, 2));
        jTextFieldNome.setDocument(new LimitaQtdaCaracteres(254));

        //jFormattedTextFieldData.setFormatterFactory(Mascara.setMaskData());
        jFormattedTextFieldCNPJ.setFormatterFactory(Mascara.setMaskCNPJ());

        Eventos.mudacorfoco(jFormattedTextFieldCNPJ);
        //Eventos.mudacorfoco(jFormattedTextFieldData);
        Eventos.mudacorfoco(jTextFieldNomeP);
        Eventos.mudacorfoco(jTextFieldUnidadeP);
        Eventos.mudacorfoco(jTextFieldValor);
        Eventos.mudacorfoco(jTextFieldNome);
        Eventos.mudacorfoco(jTextFieldValorprod);
        Eventos.mudacorfoco(jTextFieldNS);
        Eventos.mudacorfoco(jTextFieldNumero);
        Eventos.mudacorfoco(jTextFieldQuantidade);

    
    }
    
    public void ListarProdutos(int idNota){
         String[] Colunas = {"ID_Produto","Nome","Unidade","Quantidade","Valor"};
        DefaultTableModel TableModel = new DefaultTableModel (null,Colunas);
               Nf_ProdutosDAO pDao = new Nf_ProdutosDAO();
               
               ArrayList<Nf_produtosModel> prods = pDao.SelecionaPorID(""+idNota);
        for (int i=0; i<prods.size(); i++){
            Nf_produtosModel TempNFs = (Nf_produtosModel) prods.get(i);
            Object [] Linhas = {TempNFs.getProduto().getId_produto(),TempNFs.getProduto().getNome(),TempNFs.getProduto().getUnidade(),TempNFs.getQuantidade(),TempNFs.getValor()};
            TableModel.addRow(Linhas);
            
        }
            jTableProdNF.setModel(TableModel);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNS = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonAdicionarNF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNomeP = new javax.swing.JTextField();
        jTextFieldUnidadeP = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldValorprod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAdicionarP = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonBuscaProduto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProdNF = new javax.swing.JTable();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jButtonNovoFornecedor2 = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonConcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Pages/NotasFiscais/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("NotasFiscais.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 37, -1, -1));

        jTextFieldNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNumeroKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 99, 156, -1));

        jLabel2.setText(bundle.getString("NotasFiscais.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 79, -1, -1));

        jTextFieldNS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNSKeyTyped(evt);
            }
        });
        getContentPane().add(jTextFieldNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 99, 143, -1));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 148, 156, -1));
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 203, 156, -1));

        jLabel3.setText(bundle.getString("NotasFiscais.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 79, -1, -1));

        jLabel4.setText(bundle.getString("NotasFiscais.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, -1, -1));

        jLabel5.setText(bundle.getString("NotasFiscais.jLabel5.text")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 123, -1, -1));

        jLabel6.setText(bundle.getString("NotasFiscais.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 183, -1, -1));

        jButtonAdicionarNF.setText(bundle.getString("NotasFiscais.jButtonAdicionarNF.text")); // NOI18N
        jButtonAdicionarNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarNFActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdicionarNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 234, -1, -1));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeKeyTyped(evt);
            }
        });

        jLabel8.setText(bundle.getString("NotasFiscais.jLabel8.text")); // NOI18N

        jLabel9.setText(bundle.getString("NotasFiscais.jLabel9.text")); // NOI18N

        jLabel10.setText(bundle.getString("NotasFiscais.jLabel10.text")); // NOI18N

        jLabel11.setText(bundle.getString("NotasFiscais.jLabel11.text")); // NOI18N

        jButtonAdicionarP.setText(bundle.getString("NotasFiscais.jButtonAdicionarP.text")); // NOI18N
        jButtonAdicionarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPActionPerformed(evt);
            }
        });

        jLabel12.setText(bundle.getString("NotasFiscais.jLabel12.text")); // NOI18N

        jButton2.setText(bundle.getString("NotasFiscais.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaZika/LUPA.png"))); // NOI18N
        jButtonBuscaProduto.setText(bundle.getString("NotasFiscais.jButtonBuscaProduto.text")); // NOI18N
        jButtonBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jButtonAdicionarP)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeP)
                                    .addComponent(jTextFieldUnidadeP)
                                    .addComponent(jTextFieldQuantidade)
                                    .addComponent(jTextFieldValorprod, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBuscaProduto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUnidadeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdicionarP)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 24, -1, -1));

        jLabel13.setText(bundle.getString("NotasFiscais.jLabel13.text")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 329, -1, -1));

        jTableProdNF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableProdNF);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 363, -1, 99));

        jFormattedTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCNPJActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 143, 150, -1));

        jButtonNovoFornecedor2.setText(bundle.getString("NotasFiscais.jButtonNovoFornecedor2.text")); // NOI18N
        jButtonNovoFornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoFornecedor2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovoFornecedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 45, -1, -1));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaZika/LUPA.png"))); // NOI18N
        jButtonBuscar.setText(bundle.getString("NotasFiscais.jButtonBuscar.text")); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jButtonConcluir.setText("Concluir");
        jButtonConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, -1, -1));

        btnEditar.setText("Editar NF");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 90, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNumeroKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }

        int numerocaracteres = 10;
        if (jTextFieldNumero.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(jButtonAdicionarNF, "No maximo 11 caracteres no campo");

        }
    }//GEN-LAST:event_jTextFieldNumeroKeyTyped

    private void jTextFieldNSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNSKeyTyped
        // TODO add your handling code here:
        //Recebe eventokeytyped somente numeros:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
        int numerocaracteres = 45;
        if (jTextFieldNS.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(jButtonAdicionarNF, "No maximo 45 caracteres no campo");
        }
    }//GEN-LAST:event_jTextFieldNSKeyTyped

    private void jButtonAdicionarNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarNFActionPerformed
        // TODO add your handling code here:

        Color danger = new Color(214, 135, 135);
        Color success = new Color(135, 214, 137);
        Boolean validator = true;
 
        if (jTextFieldNome.getText().trim().length() > 0 && jTextFieldNome.getText().length() <= 254) {
            jTextFieldNome.setBackground(success);
        } else {
            jTextFieldNome.setBackground(danger);
            validator = false;
        }

//        if (jFormattedTextFieldData.getText().replace("_", "").replace("/", "").trim().length() > 0 && jFormattedTextFieldData.getText().length() <= 10) {
//            jFormattedTextFieldData.setBackground(success);
//        } else {
//            jFormattedTextFieldData.setBackground(danger);
//        }
        if (jFormattedTextFieldCNPJ.getText().replace("_", "").replace("/", "").trim().length() > 0 && jFormattedTextFieldCNPJ.getText().length() <= 11) {
            jFormattedTextFieldCNPJ.setBackground(success);
        } else {
            jFormattedTextFieldCNPJ.setBackground(danger);
            validator = false;
        }
        if (jTextFieldNumero.getText().length() > 0 && jTextFieldNumero.getText().length() <= 11) {
            jTextFieldNumero.setBackground(success);
        } else {
            jTextFieldNumero.setBackground(danger);
            validator = false;
        }
        if (jTextFieldNS.getText().length() > 0 && jTextFieldNS.getText().length() <= 45) {
            jTextFieldNS.setBackground(success);
        } else {
            jTextFieldNS.setBackground(danger);
            validator = false;
        }
        if (jTextFieldValor.getText().length() > 0 && jTextFieldValor.getText().length() <= 13) {
            jTextFieldValor.setBackground(success);
        } else {
            jTextFieldValor.setBackground(danger);
            validator = false;

        }
        
        if (validator == true){
            
        try {
                            PreparedStatement pst = conecta.getConnection().prepareStatement("insert into nf(numero,serie,valor,data,id_fornecedor)values(?,?,?,(select now()),?)",Statement.RETURN_GENERATED_KEYS);
                            pst.setString(1, jTextFieldNumero.getText());
                            pst.setString(2, jTextFieldNS.getText());
                            pst.setString(3, jTextFieldValor.getText());
                            pst.setInt(4, idF);
                            
                           
            
                            pst.executeUpdate();
                            ResultSet rs = pst.getGeneratedKeys();
                            if(rs.next()){
                                ultimoID = rs.getInt(1);
                            }
                            
                            JOptionPane.showMessageDialog(rootPane, "Nota Fiscal cadastrada com sucesso!");
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Erro na inserção! \n ERRO:!" + ex + "  chame o tecnico!!");;
                        }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatorios que estão destacados em vermelho");
        }
        jButtonAdicionarNF.setEnabled(false);
    }//GEN-LAST:event_jButtonAdicionarNFActionPerformed

    private void jTextFieldQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }

        int numerocaracteres = 11;
        if (jTextFieldQuantidade.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(jButtonAdicionarP, "No maximo 11 caracteres no campo");

        }
    }//GEN-LAST:event_jTextFieldQuantidadeKeyTyped

    private void jButtonAdicionarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPActionPerformed
        // TODO add your handling code here:
        Color danger = new Color(214, 135, 135);
        Color success = new Color(135, 214, 137);
        Boolean validator = true;

        if (jTextFieldNomeP.getText().trim().length() > 0 && jTextFieldNomeP.getText().length() <= 254) {
            jTextFieldNomeP.setBackground(success);
        } else {
            jTextFieldNomeP.setBackground(danger);
             validator = false;
        }

        if (jTextFieldUnidadeP.getText().trim().length() > 0 && jTextFieldUnidadeP.getText().length() <= 254) {
            jTextFieldUnidadeP.setBackground(success);
        } else {
            jTextFieldUnidadeP.setBackground(danger);
             validator = false;
        }

        if (jTextFieldQuantidade.getText().trim().length() > 0 && jTextFieldQuantidade.getText().length() <= 11) {
            jTextFieldQuantidade.setBackground(success);
        } else {
            jTextFieldQuantidade.setBackground(danger);
             validator = false;
        }

        if (jTextFieldValorprod.getText().trim().length() > 0 && jTextFieldValorprod.getText().length() <= 20) {
            jTextFieldValorprod.setBackground(success);
        } else {
            jTextFieldValorprod.setBackground(danger);
             validator = false;
        }
         if (validator == true){
        try {
                            PreparedStatement pst2 = conecta.getConnection().prepareStatement("insert into nf_produtos(id_nf,id_produto,quantidade,valor)values(?,?,?,?)");
                            pst2.setInt(1, ultimoID);
                            pst2.setInt(2, idP);
                            pst2.setInt(3, Integer.parseInt(jTextFieldQuantidade.getText()));
                            pst2.setString(4, jTextFieldValor.getText());
                            
                            
                           
            
                            pst2.executeUpdate();
                            ListarProdutos(ultimoID);
                            JOptionPane.showMessageDialog(rootPane, "Produto Cadastrado na NOTA com sucesso!");
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Erro na inserção! \n ERRO:!" + ex + " Insira Primeiro os Dados da Nota ");;
                        }
        }else{
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatorios que estão destacados em vermelho");
        }
        jTextFieldNomeP.setText("");
        jTextFieldUnidadeP.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldValorprod.setText("");
        
         
    }//GEN-LAST:event_jButtonAdicionarPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame addProduto = new AddProdutos();
        addProduto.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutoActionPerformed
        JFrame addProdutos = new BuscarProdutos();
        addProdutos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscaProdutoActionPerformed

    private void jFormattedTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCNPJActionPerformed

    private void jButtonNovoFornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoFornecedor2ActionPerformed
        // TODO add your handling code here:
        JFrame addFornecedor = new AddFornecedor();
        addFornecedor.setVisible(true);
    }//GEN-LAST:event_jButtonNovoFornecedor2ActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        JFrame BuscarFornecedor = new BuscarFornecedor();
        BuscarFornecedor.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonConcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        NF.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
        NF.setSerie(jTextFieldNS.getText());
        NF.setId_fornecedor(idF);
        NF.setValor(Double.parseDouble(jTextFieldValor.getText()));
        
         nfdao.Editar(NF);
        JOptionPane.showMessageDialog(null, "Editado com Sucesso");
       
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDNotasFiscais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDNotasFiscais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDNotasFiscais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDNotasFiscais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDNotasFiscais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionarNF;
    private javax.swing.JButton jButtonAdicionarP;
    private javax.swing.JButton jButtonBuscaProduto;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonConcluir;
    private javax.swing.JButton jButtonNovoFornecedor2;
    public static javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdNF;
    private javax.swing.JTextField jTextFieldNS;
    public static javax.swing.JTextField jTextFieldNome;
    public static javax.swing.JTextField jTextFieldNomeP;
    public static javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldQuantidade;
    public static javax.swing.JTextField jTextFieldUnidadeP;
    public static javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldValorprod;
    // End of variables declaration//GEN-END:variables
}
