/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.NotasFiscais;

import SistemaZika.Aplicacao;
import SistemaZika.DAO.NFDAO;
import SistemaZika.Models.ModelNF;
import SistemaZika.SearchJTable;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Nunes
 */
public class ListaNotasFiscais extends javax.swing.JPanel {

    /**
     * Creates new form ListaNotasFiscais
     */
    public ListaNotasFiscais() {
        initComponents();
       NFDAO nfDAO= new NFDAO();
        ArrayList<ModelNF> NF = nfDAO.SelecionaTudo();
        
        //jTableProdutos
        String[] Colunas = {"id_nf","numero","serie","valor","data","id_fornecedor"};
        DefaultTableModel TableModel = new DefaultTableModel (null,Colunas);
                
        for (int i=0; i<NF.size(); i++){
            ModelNF TempNFs = (ModelNF) NF.get(i);
            Object [] Linhas = {TempNFs.getId_nf(),TempNFs.getNumero(),TempNFs.getSerie(),TempNFs.getValor(),TempNFs.getData(),TempNFs.getId_fornecedor()};
            TableModel.addRow(Linhas);
            
        }
            jTableNotas.setModel(TableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBuscarNF = new javax.swing.JTextField();
        jButtonAtualizaT = new javax.swing.JButton();
        jButtonEditarNF = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Pages/NotasFiscais/Bundle"); // NOI18N
        jButton1.setText(bundle.getString("NotasFiscais.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableNotas);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Notas Fiscais:");

        jTextFieldBuscarNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarNFKeyTyped(evt);
            }
        });

        jButtonAtualizaT.setText("Atualizar Tabela");
        jButtonAtualizaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizaTActionPerformed(evt);
            }
        });

        jButtonEditarNF.setText("Editar NF");
        jButtonEditarNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarNFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButtonAtualizaT))
                        .addGap(220, 220, 220)
                        .addComponent(jTextFieldBuscarNF, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditarNF, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextFieldBuscarNF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAtualizaT)
                    .addComponent(jButtonEditarNF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame ADDNotasFiscais = new ADDNotasFiscais();
        ADDNotasFiscais.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAtualizaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizaTActionPerformed
        // TODO add your handling code here:
        //Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel AtualizaNF = new ListaNotasFiscais();
        Aplicacao.Corpo.add(AtualizaNF, BorderLayout.CENTER);
        ListaNotasFiscais.jTextFieldBuscarNF.requestFocus();
    }//GEN-LAST:event_jButtonAtualizaTActionPerformed

    private void jButtonEditarNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarNFActionPerformed
        // TODO add your handling code here:
        
       int linha = jTableNotas.getSelectedRow();
        if (linha != -1){
            Object idNota = jTableNotas.getValueAt(linha, 0);
            if(Integer.parseInt(idNota.toString())!= -1){
               ADDNotasFiscais verNF = new ADDNotasFiscais(idNota.toString());
               verNF.setVisible(true);
            }
        }else{
        JOptionPane.showMessageDialog(null, "Selecione a linha que deseja editar");}
    }//GEN-LAST:event_jButtonEditarNFActionPerformed

    private void jTextFieldBuscarNFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarNFKeyTyped
        // TODO add your handling code here:
        SearchJTable.SearchJTable(jTableNotas, jTextFieldBuscarNF);
        
    }//GEN-LAST:event_jTextFieldBuscarNFKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAtualizaT;
    private javax.swing.JButton jButtonEditarNF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNotas;
    public static javax.swing.JTextField jTextFieldBuscarNF;
    // End of variables declaration//GEN-END:variables
}
