/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.NotasFiscais;

import SistemaZika.DAO.SqlConecta;
import SistemaZika.Eventos;
import SistemaZika.FormataDecimalCampo;
import SistemaZika.LimitaQtdaCaracteres;
import SistemaZika.Mascara;
import static exemplo.Componente.Menu.btnNotasFiscais;
import exemplo.Pages.Fornecedores.AddFornecedor;
import exemplo.Pages.Produtos.AddProdutos;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Nunes
 */
public class NotasFiscais extends javax.swing.JPanel {

    /**
     * Creates new form NotasFiscais
     * 
     */
     public static int idF;
     public static int idP;
     SqlConecta conecta = new SqlConecta();
    public NotasFiscais() {
        initComponents();
        //btnNotasFiscais.setFocusable(false);
        jTextFieldNF.setFocusable(true);
        //jTextFieldNF.setRequestFocusEnabled(true);
        jTextFieldNF.requestFocus();
        jTextFieldValor.setDocument(new FormataDecimalCampo(10, 2));
        jTextFieldValorprod.setDocument(new FormataDecimalCampo(10, 2));
        jTextFieldNome.setDocument(new LimitaQtdaCaracteres(254));

        jFormattedTextFieldData.setFormatterFactory(Mascara.setMaskData());
        jFormattedTextFieldCNPJ.setFormatterFactory(Mascara.setMaskCNPJ());

        Eventos.mudacorfoco(jFormattedTextFieldCNPJ);
        Eventos.mudacorfoco(jFormattedTextFieldData);
        Eventos.mudacorfoco(jTextFieldNomeP);
        Eventos.mudacorfoco(jTextFieldUnidadeP);
        Eventos.mudacorfoco(jTextFieldValor);
        Eventos.mudacorfoco(jTextFieldNome);
        Eventos.mudacorfoco(jTextFieldValorprod);
        Eventos.mudacorfoco(jTextFieldNS);
        Eventos.mudacorfoco(jTextFieldNF);
        Eventos.mudacorfoco(jTextFieldQuantidade);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNS = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonAdicionarNF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldNomeP = new javax.swing.JTextField();
        jTextFieldUnidadeP = new javax.swing.JTextField();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jTextFieldValorprod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonAdicionarP = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonBuscaProduto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jButtonNovoFornecedor2 = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Pages/NotasFiscais/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("NotasFiscais.jLabel1.text")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        jTextFieldNF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNFKeyTyped(evt);
            }
        });
        add(jTextFieldNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 156, -1));

        jLabel2.setText(bundle.getString("NotasFiscais.jLabel2.text")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jTextFieldNS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNSKeyTyped(evt);
            }
        });
        add(jTextFieldNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 86, 143, -1));
        add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 156, -1));
        add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 156, -1));

        jLabel3.setText(bundle.getString("NotasFiscais.jLabel3.text")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 66, -1, -1));

        jLabel4.setText(bundle.getString("NotasFiscais.jLabel4.text")); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        jLabel5.setText(bundle.getString("NotasFiscais.jLabel5.text")); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel6.setText(bundle.getString("NotasFiscais.jLabel6.text")); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel7.setText(bundle.getString("NotasFiscais.jLabel7.text")); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        jButtonAdicionarNF.setText(bundle.getString("NotasFiscais.jButtonAdicionarNF.text")); // NOI18N
        jButtonAdicionarNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarNFActionPerformed(evt);
            }
        });
        add(jButtonAdicionarNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantidadeKeyTyped(evt);
            }
        });

        jLabel8.setText(bundle.getString("NotasFiscais.jLabel8.text")); // NOI18N

        jLabel9.setText(bundle.getString("NotasFiscais.jLabel9.text")); // NOI18N

        jLabel10.setText(bundle.getString("NotasFiscais.jLabel10.text")); // NOI18N

        jLabel11.setText(bundle.getString("NotasFiscais.jLabel11.text")); // NOI18N

        jButtonAdicionarP.setText(bundle.getString("NotasFiscais.jButtonAdicionarP.text")); // NOI18N
        jButtonAdicionarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarPActionPerformed(evt);
            }
        });

        jLabel12.setText(bundle.getString("NotasFiscais.jLabel12.text")); // NOI18N

        jButton2.setText(bundle.getString("NotasFiscais.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonBuscaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaZika/LUPA.png"))); // NOI18N
        jButtonBuscaProduto.setText(bundle.getString("NotasFiscais.jButtonBuscaProduto.text")); // NOI18N
        jButtonBuscaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jButtonAdicionarP)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNomeP)
                                    .addComponent(jTextFieldUnidadeP)
                                    .addComponent(jTextFieldQuantidade)
                                    .addComponent(jTextFieldValorprod, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonBuscaProduto)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUnidadeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdicionarP)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 11, -1, -1));

        jLabel13.setText(bundle.getString("NotasFiscais.jLabel13.text")); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 316, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Nota", "Produtos"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("NotasFiscais.jTable2.columnModel.title0")); // NOI18N
            jTable2.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("NotasFiscais.jTable2.columnModel.title1")); // NOI18N
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 99));

        jFormattedTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataActionPerformed(evt);
            }
        });
        add(jFormattedTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 149, -1));

        jFormattedTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCNPJActionPerformed(evt);
            }
        });
        add(jFormattedTextFieldCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, -1));

        jButtonNovoFornecedor2.setText(bundle.getString("NotasFiscais.jButtonNovoFornecedor2.text")); // NOI18N
        jButtonNovoFornecedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoFornecedor2ActionPerformed(evt);
            }
        });
        add(jButtonNovoFornecedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 32, -1, -1));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaZika/LUPA.png"))); // NOI18N
        jButtonBuscar.setText(bundle.getString("NotasFiscais.jButtonBuscar.text")); // NOI18N
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jButton1.setText(bundle.getString("NotasFiscais.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoFornecedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoFornecedor2ActionPerformed
        // TODO add your handling code here:
        JFrame addFornecedor = new AddFornecedor();
        addFornecedor.setVisible(true);
    }//GEN-LAST:event_jButtonNovoFornecedor2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame addProduto = new AddProdutos();
        addProduto.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAdicionarNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarNFActionPerformed
        // TODO add your handling code here:

        Color danger = new Color(214, 135, 135);
        Color success = new Color(135, 214, 137);

        if (jTextFieldNome.getText().trim().length() > 0 && jTextFieldNome.getText().length() <= 254) {
            jTextFieldNome.setBackground(success);
        } else {
            jTextFieldNome.setBackground(danger);
        }

        if (jFormattedTextFieldData.getText().replace("_", "").replace("/", "").trim().length() > 0 && jFormattedTextFieldData.getText().length() <= 10) {
            jFormattedTextFieldData.setBackground(success);
        } else {
            jFormattedTextFieldData.setBackground(danger);
        }
        if (jFormattedTextFieldCNPJ.getText().replace("_", "").replace("/", "").trim().length() > 0 && jFormattedTextFieldCNPJ.getText().length() <= 11) {
            jFormattedTextFieldCNPJ.setBackground(success);
        } else {
            jFormattedTextFieldCNPJ.setBackground(danger);
        }
        if (jTextFieldNF.getText().length() > 0 && jTextFieldNF.getText().length() <= 11) {
            jTextFieldNF.setBackground(success);
        } else {
            jTextFieldNF.setBackground(danger);
        }
        if (jTextFieldNS.getText().length() > 0 && jTextFieldNS.getText().length() <= 45) {
            jTextFieldNS.setBackground(success);
        } else {
            jTextFieldNS.setBackground(danger);
        }
        if (jTextFieldValor.getText().length() > 0 && jTextFieldValor.getText().length() <= 13) {
            jTextFieldValor.setBackground(success);
        } else {
            jTextFieldValor.setBackground(danger);

        }

//try {
//                PreparedStatement pst = conecta.getConnection().prepareStatement("insert into nf(nome,cnpj,telefone,status)values(?,?,?,?)");
//                pst.setString(1, jTextFieldNomeF.getText().replace("_", "").replace("/", "").trim());
//                pst.setString(2, jFormattedTextFieldCNPJ.getText().replace("_", "").replace("/", "").trim());
//                pst.setString(3, jFormattedTextFieldTelefone.getText().replace("_", "").replace("(", "").replace("-", "").replace(")", "").trim());
//                pst.setInt(4, jComboBoxStatusF.getSelectedIndex());
//
//                pst.executeUpdate();
//                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(rootPane, "Erro na inserção! \n ERRO:!" + ex + "  chame o tecnico!!");;
//            }
    }//GEN-LAST:event_jButtonAdicionarNFActionPerformed

    private void jTextFieldNFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNFKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }

        int numerocaracteres = 11;
        if (jTextFieldNF.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(jButtonAdicionarNF, "No maximo 11 caracteres no campo");

        }

    }//GEN-LAST:event_jTextFieldNFKeyTyped

    private void jTextFieldNSKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNSKeyTyped
        // TODO add your handling code here:
        //Recebe eventokeytyped somente numeros:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
        int numerocaracteres = 45;
        if (jTextFieldNS.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(jButtonAdicionarNF, "No maximo 45 caracteres no campo");
        }
    }//GEN-LAST:event_jTextFieldNSKeyTyped

    private void jFormattedTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataActionPerformed

    private void jFormattedTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCNPJActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jFormattedTextFieldCNPJActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        JFrame BuscarFornecedor = new BuscarFornecedor();
        BuscarFornecedor.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBuscaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaProdutoActionPerformed
        JFrame addProdutos = new BuscarProdutos();
        addProdutos.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscaProdutoActionPerformed

    private void jButtonAdicionarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarPActionPerformed
        // TODO add your handling code here:
        Color danger = new Color(214, 135, 135);
        Color success = new Color(135, 214, 137);

        if (jTextFieldNomeP.getText().trim().length() > 0 && jTextFieldNomeP.getText().length() <= 254) {
            jTextFieldNomeP.setBackground(success);
        } else {
            jTextFieldNomeP.setBackground(danger);
        }

        if (jTextFieldUnidadeP.getText().trim().length() > 0 && jTextFieldUnidadeP.getText().length() <= 254) {
            jTextFieldUnidadeP.setBackground(success);
        } else {
            jTextFieldUnidadeP.setBackground(danger);
        }

        if (jTextFieldQuantidade.getText().trim().length() > 0 && jTextFieldQuantidade.getText().length() <= 11) {
            jTextFieldQuantidade.setBackground(success);
        } else {
            jTextFieldQuantidade.setBackground(danger);
        }

        if (jTextFieldValorprod.getText().trim().length() > 0 && jTextFieldValorprod.getText().length() <= 20) {
            jTextFieldValorprod.setBackground(success);
        } else {
            jTextFieldValorprod.setBackground(danger);
        }
    }//GEN-LAST:event_jButtonAdicionarPActionPerformed

    private void jTextFieldQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeKeyTyped
        // TODO add your handling code here:
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }

        int numerocaracteres = 11;
        if (jTextFieldQuantidade.getText().length() >= numerocaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(jButtonAdicionarP, "No maximo 11 caracteres no campo");

        }
    }//GEN-LAST:event_jTextFieldQuantidadeKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame ADDNotasFiscais = new ADDNotasFiscais();
        ADDNotasFiscais.setVisible(true);   
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionarNF;
    private javax.swing.JButton jButtonAdicionarP;
    private javax.swing.JButton jButtonBuscaProduto;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonNovoFornecedor2;
    public static javax.swing.JFormattedTextField jFormattedTextFieldCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JTextField jTextFieldNF;
    private javax.swing.JTextField jTextFieldNS;
    public static javax.swing.JTextField jTextFieldNome;
    public static javax.swing.JTextField jTextFieldNomeP;
    private javax.swing.JTextField jTextFieldQuantidade;
    public static javax.swing.JTextField jTextFieldUnidadeP;
    public static javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldValorprod;
    // End of variables declaration//GEN-END:variables
}
