/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaZika;

import SistemaZika.DAO.ProdutoDAO;
import exemplo.Componente.Menu;
import exemplo.Pages.Dashboard.Dashboard;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Leonardo Nunes
 */
public class Aplicacao extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacao
     */
    public Aplicacao() {
        initComponents();

        JPanel menu = new Menu();
        Topo.add(menu, BorderLayout.CENTER);

        JPanel dashboard = new Dashboard();
        Corpo.add(dashboard, BorderLayout.CENTER);
        Eventos.setAcessibilidade(this);
        Eventos.Acelerador(this);

        ProdutoDAO DAO = new ProdutoDAO();
        DAO.SelecionaTudo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Corpo = new javax.swing.JPanel();
        Topo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Corpo.setBackground(new java.awt.Color(204, 255, 204));
        Corpo.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Corpo, java.awt.BorderLayout.CENTER);

        Topo.setBackground(new java.awt.Color(204, 204, 255));
        Topo.setPreferredSize(new java.awt.Dimension(400, 50));
        Topo.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Topo, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        String[] options = new String[]{
            ("Continuar"),
            ("Minimizar"),
            ("Sair")
        };
        int Answer = JOptionPane.showOptionDialog(null, ("Deseja realmente SAIR???"), "",
                JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

        if (Answer == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        } else if (Answer == JOptionPane.CANCEL_OPTION) {
            System.exit(0);
        } else {
            this.setVisible(false);
            TrayClass tray = new TrayClass();

        }

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel Corpo;
    private javax.swing.JPanel Topo;
    // End of variables declaration//GEN-END:variables
}
