/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Componente;

import SistemaZika.Aplicacao;
import exemplo.Pages.Dashboard.Dashboard;
import exemplo.Pages.Fornecedores.AddFornecedor;
import exemplo.Pages.Fornecedores.Fornecedores;
import exemplo.Pages.NotasFiscais.ListaNotasFiscais;
import exemplo.Pages.NotasFiscais.NotasFiscais;
import exemplo.Pages.Pedidos.Pedidos;
import exemplo.Pages.Produtos.AddProdutos;
import exemplo.Pages.Produtos.Produtos;
import exemplo.Pages.Relatórios.Relatorios;
import exemplo.Pages.SeusDados.SeusDados;
import exemplo.Pages.Usuários.Usuarios;
import exemplo.Pages.Usuários.lUsuarios;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Leonardo Nunes
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnDashboard = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        btnNotasFiscais = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnSeusDados = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Componente/Bundle"); // NOI18N
        jMenuItem1.setText(bundle.getString("Menu.jMenuItem1.text")); // NOI18N
        jMenuItem1.setToolTipText(bundle.getString("Menu.jMenuItem1.toolTipText")); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText(bundle.getString("Menu.jMenuItem2.text")); // NOI18N
        jMenuItem2.setComponentPopupMenu(jPopupMenu2);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(400, 50));

        btnDashboard.setText(bundle.getString("Menu.btnDashboard.text")); // NOI18N
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnFornecedores.setText(bundle.getString("Menu.btnFornecedores.text")); // NOI18N
        btnFornecedores.setComponentPopupMenu(jPopupMenu1);
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });

        btnNotasFiscais.setText(bundle.getString("Menu.btnNotasFiscais.text")); // NOI18N
        btnNotasFiscais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasFiscaisActionPerformed(evt);
            }
        });

        btnProdutos.setText(bundle.getString("Menu.btnProdutos.text")); // NOI18N
        btnProdutos.setComponentPopupMenu(jPopupMenu2);
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnUsuarios.setText(bundle.getString("Menu.btnUsuarios.text")); // NOI18N
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnPedidos.setText(bundle.getString("Menu.btnPedidos.text")); // NOI18N
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnSeusDados.setText(bundle.getString("Menu.btnSeusDados.text")); // NOI18N
        btnSeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeusDadosActionPerformed(evt);
            }
        });

        btnRelatorios.setText(bundle.getString("Menu.btnRelatorios.text")); // NOI18N
        btnRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDashboard)
                .addGap(2, 2, 2)
                .addComponent(btnFornecedores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNotasFiscais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeusDados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDashboard)
                    .addComponent(btnFornecedores)
                    .addComponent(btnNotasFiscais)
                    .addComponent(btnProdutos)
                    .addComponent(btnUsuarios)
                    .addComponent(btnRelatorios)
                    .addComponent(btnPedidos)
                    .addComponent(btnSeusDados))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel dashboard = new Dashboard();
        Aplicacao.Corpo.add(dashboard, BorderLayout.CENTER);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        // TODO add your handling code here:
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel fornecedores = new Fornecedores();
        Aplicacao.Corpo.add(fornecedores, BorderLayout.CENTER);
        Fornecedores.jTextFieldPesquisar.requestFocus();
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnSeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeusDadosActionPerformed
        // TODO add your handling code here:
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel seusdados = new SeusDados();
        Aplicacao.Corpo.add(seusdados, BorderLayout.CENTER);
    }//GEN-LAST:event_btnSeusDadosActionPerformed

    private void btnNotasFiscaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasFiscaisActionPerformed
        // TODO add your handling code here:
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel notasfiscais = new ListaNotasFiscais();
        Aplicacao.Corpo.add(notasfiscais, BorderLayout.CENTER);
        ListaNotasFiscais.jTextFieldBuscarNF.requestFocus();
      
    }//GEN-LAST:event_btnNotasFiscaisActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        // TODO add your handling code here:
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel produtos = new Produtos();
        Aplicacao.Corpo.add(produtos, BorderLayout.CENTER);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel listarUsuarios = new lUsuarios();
        Aplicacao.Corpo.add(listarUsuarios, BorderLayout.CENTER);
        //lUsuarios.jButtonAddUsuario.requestFocus();
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        // TODO add your handling code here:
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel relatorios = new Relatorios();
        Aplicacao.Corpo.add(relatorios, BorderLayout.CENTER);
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        // TODO add your handling code here:Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel pedidos = new Pedidos();
        Aplicacao.Corpo.add(pedidos, BorderLayout.CENTER);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
      JFrame addFornecedor = new AddFornecedor();
        addFornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFrame addProduto = new AddProdutos();
        addProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    public static javax.swing.JButton btnFornecedores;
    public static javax.swing.JButton btnNotasFiscais;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSeusDados;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
