/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.Usuários;

import SistemaZika.DAO.SqlConecta;
import SistemaZika.DAO.UsuarioDAO;
import SistemaZika.Eventos;
import SistemaZika.LimitaQtdaCaracteres;
import SistemaZika.Mascara;
import SistemaZika.Models.UsuarioModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo Nunes
 */
public class AddUsuarios extends javax.swing.JFrame {

    SqlConecta conecta = new SqlConecta();
    private UsuarioModel usuario;
    private UsuarioDAO udao;

    /**
     * Creates new form AddUsuarios
     */
    public AddUsuarios() {
        initPage();
        jButtonEditar.setVisible(false);
        

    }

    public AddUsuarios(String id_usuario) {
        initPage();
        jButton1.setVisible(false);
        udao = new UsuarioDAO();
        usuario = udao.SelecionaPorID(id_usuario);
        jTextFieldNome.setText(usuario.getNome());
        jFormattedTextFieldCPF.setText(usuario.getCpf());
        jComboBoxSexo.setSelectedItem(usuario.getSexo());
        jFormattedTextFieldDATAN.setText(usuario.getNascimento().toString().replace("-", ""));
        jFormattedTextFieldTelFixo.setText(usuario.getTel_fixo());
        jFormattedTextFieldCelular.setText(usuario.getTel_celular());
        jTextFieldEmail.setText(usuario.getEmail());
        jComboBoxGrupo.setSelectedItem(usuario.getGrupo());
        jComboBoxSETOR.setSelectedItem(usuario.getSetor());
        jTextFieldUserName.setText(usuario.getUsarname());
        jTextFieldSENHA.setText(usuario.getSenha());

        jComboBoxStatus.setSelectedIndex(usuario.getStatus());

    }

    public void initPage() {
        initComponents();

        Eventos.setAcessibilidade(this);
        jTextFieldNome.setFocusable(true);
        jTextFieldNome.requestFocus();
        jFormattedTextFieldCPF.setFormatterFactory(Mascara.setMaskCPF());
        jFormattedTextFieldDATAN.setFormatterFactory(Mascara.setMaskData());
        jFormattedTextFieldTelFixo.setFormatterFactory(Mascara.setMaskTelFixo());
        jFormattedTextFieldCelular.setFormatterFactory(Mascara.setMaskCelular());
        jTextFieldNome.setDocument(new LimitaQtdaCaracteres(255));
        jTextFieldEmail.setDocument(new LimitaQtdaCaracteres(45));
        jTextFieldNome.setDocument (new LimitaQtdaCaracteres(45));
        jTextFieldSENHA.setDocument (new LimitaQtdaCaracteres(254));
        jTextFieldUserName.setDocument (new LimitaQtdaCaracteres(45));
        

        Eventos.mudacorfoco(jTextFieldEmail);
        Eventos.mudacorfoco(jFormattedTextFieldCPF);
        Eventos.mudacorfoco(jTextFieldNome);
        Eventos.mudacorfoco(jFormattedTextFieldCelular);
        Eventos.mudacorfoco(jFormattedTextFieldDATAN);
        Eventos.mudacorfoco(jFormattedTextFieldTelFixo);
        Eventos.mudacorfoco(jTextFieldUserName);
        Eventos.mudacorfoco(jTextFieldSENHA);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jComboBoxSETOR = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxGrupo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDATAN = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelFixo = new javax.swing.JFormattedTextField();
        jTextFieldSENHA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exemplo/Pages/Usuários/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("Usuarios.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, -1));

        jLabel2.setText(bundle.getString("Usuarios.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setText(bundle.getString("Usuarios.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText(bundle.getString("Usuarios.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        getContentPane().add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText(bundle.getString("Usuarios.jLabel5.text")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText(bundle.getString("Usuarios.jLabel6.text")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        jLabel7.setText(bundle.getString("Usuarios.jLabel7.text")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel8.setText(bundle.getString("Usuarios.jLabel8.text")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 140, -1));

        jComboBoxSETOR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerencia", "Escritório", "Almoxarifado", " " }));
        getContentPane().add(jComboBoxSETOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel9.setText(bundle.getString("Usuarios.jLabel9.text")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jComboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Almoxarifado", "Usuario" }));
        getContentPane().add(jComboBoxGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jButton1.setText(bundle.getString("Usuarios.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));
        getContentPane().add(jFormattedTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 140, -1));
        getContentPane().add(jFormattedTextFieldDATAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 89, -1));

        jLabel10.setText(bundle.getString("Usuarios.jLabel10.text")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));
        getContentPane().add(jFormattedTextFieldCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 130, -1));
        getContentPane().add(jFormattedTextFieldTelFixo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, -1));

        jTextFieldSENHA.setText(bundle.getString("Usuarios.jTextFieldSENHA.text")); // NOI18N
        getContentPane().add(jTextFieldSENHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 140, -1));

        jLabel11.setText(bundle.getString("Usuarios.jLabel11.text")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inativo", "Ativo" }));
        getContentPane().add(jComboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel12.setText(bundle.getString("Usuarios.jLabel12.text")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel13.setText(bundle.getString("Usuarios.jLabel13.text")); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel14.setText(bundle.getString("Usuarios.jLabel14.text")); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jTextFieldUserName.setText(bundle.getString("Usuarios.jTextFieldUserName.text")); // NOI18N
        getContentPane().add(jTextFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, -1));

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText(bundle.getString("Usuarios.jLabel15.text")); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText(bundle.getString("Usuarios.jLabel16.text")); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText(bundle.getString("Usuarios.jLabel17.text")); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText(bundle.getString("Usuarios.jLabel18.text")); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setText(bundle.getString("Usuarios.jLabel19.text")); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        jLabel20.setText(".");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNome.getText().equals("")) {
            jTextFieldNome.requestFocus();
            JOptionPane.showMessageDialog(null, "O campo Nome é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jFormattedTextFieldCPF.getText().equals("___.___.___-__")) {
            jFormattedTextFieldCPF.requestFocus();
            JOptionPane.showMessageDialog(null, "O campo CPF é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jFormattedTextFieldDATAN.getText().equals("____/__/__")) {
            jFormattedTextFieldDATAN.requestFocus();
            JOptionPane.showMessageDialog(null, "O campo DATA DE NASCIMENTO é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jTextFieldUserName.getText().equals("")) {
            jTextFieldUserName.requestFocus();
            JOptionPane.showMessageDialog(null, "O campo USERNAME é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jTextFieldSENHA.getText().equals("")) {
            jTextFieldSENHA.requestFocus();
            JOptionPane.showMessageDialog(null, "O campo SENHA é obrigatório", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            PreparedStatement pst = conecta.getConnection().prepareStatement("insert into usuarios(cpf,email,grupo,nascimento,nome,senha,setor,sexo,status,tel_celular,tel_fixo,usarname)values(?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, jFormattedTextFieldCPF.getText().replace("_", "").replace("/", "").replace(".", "").replace("-", "").trim());
            pst.setString(2, jTextFieldEmail.getText());
            pst.setObject(3, jComboBoxGrupo.getSelectedItem());
            pst.setString(4, jFormattedTextFieldDATAN.getText().replace("_", "").replace("/", "").trim());
            pst.setString(5, jTextFieldNome.getText());
            pst.setString(6, jTextFieldSENHA.getText());
            pst.setObject(7, jComboBoxSETOR.getSelectedItem());
            pst.setString(8, jComboBoxSexo.getSelectedItem().toString());
            pst.setInt(9, jComboBoxStatus.getSelectedIndex());
            pst.setString(10, jFormattedTextFieldCelular.getText().replace("_", "").replace("(", "").replace("-", "").replace(")", "").trim());
            pst.setString(11, jFormattedTextFieldTelFixo.getText().replace("_", "").replace("(", "").replace("-", "").replace(")", "").trim());
            pst.setString(12, jTextFieldUserName.getText().trim());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "   Erro na inserção! \n ERRO:" + ex);
        }
        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:

//        
//        usuario = new UsuarioModel();
//        try{
//        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
//       String data = sdf.format(jFormattedTextFieldDATAN.getText());
//            System.out.println(data);
//       SimpleDateFormat sdf2 = new SimpleDateFormat ("yyyy-MM-dd");
//       Date data2 = sdf2.parse(data);
        usuario.setNome(jTextFieldNome.getText());
        usuario.setCpf(jFormattedTextFieldCPF.getText().replace("_", "").replace("/", "").replace(".", "").replace("-", "").trim());
        usuario.setEmail(jTextFieldEmail.getText());
        usuario.setGrupo(jComboBoxGrupo.getSelectedItem().toString());
        usuario.setSexo(jComboBoxSexo.getSelectedItem().toString());
        usuario.setSetor(jComboBoxSETOR.getSelectedItem().toString());
        usuario.setNascimento(jFormattedTextFieldDATAN.getText().replace("_", "").replace("/", "").trim());
        usuario.setTel_fixo(jFormattedTextFieldTelFixo.getText().replace("_", "").replace("(", "").replace("-", "").replace(")", "").trim());
        usuario.setTel_celular(jFormattedTextFieldCelular.getText().replace("_", "").replace("(", "").replace("-", "").replace(")", "").trim());
        usuario.setUsarname(jTextFieldUserName.getText());
        usuario.setSenha(jTextFieldSENHA.getText());
        usuario.setStatus(jComboBoxStatus.getSelectedIndex());

        udao.Editar(usuario);
        JOptionPane.showMessageDialog(null, "Editado com Sucesso");
        
        this.setVisible(false);
//        }catch(Exception Error){
//            System.out.println(Error);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JComboBox<String> jComboBoxGrupo;
    private javax.swing.JComboBox<String> jComboBoxSETOR;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldDATAN;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelFixo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldEmail;
    public static javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSENHA;
    private javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
