/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exemplo.Pages.Usuários;

import SistemaZika.Aplicacao;
import SistemaZika.DAO.UsuarioDAO;
import SistemaZika.Models.UsuarioModel;
import SistemaZika.SearchJTable;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo Nunes
 */
public class lUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form lUsuarios
     */
    public ArrayList<UsuarioModel> Usuarios;
    public UsuarioDAO UDAO;
    public lUsuarios() {
        initComponents();
        
        UDAO = new UsuarioDAO();
        Usuarios = UDAO.SelecionaTudo();
        
        
        String[] Colunas = {"id_usuario","nome","cpf","sexo","nascimento","tel_fixo","tel_celular","email","setor","grupo","usarname","senha","status"};
        DefaultTableModel TableModel = new DefaultTableModel (null,Colunas);
                
        for (int i=0; i<Usuarios.size(); i++){
            UsuarioModel TempUsuario = (UsuarioModel) Usuarios.get(i);
            Object [] Linhas = {TempUsuario.getId_usuario(),TempUsuario.getNome(),TempUsuario.getCpf(),TempUsuario.getSexo(),TempUsuario.getNascimento(),TempUsuario.getTel_fixo(),TempUsuario.getTel_celular(),TempUsuario.getEmail(),TempUsuario.getSetor(),TempUsuario.getGrupo(),TempUsuario.getUsarname(),TempUsuario.getSenha(),TempUsuario.getStatus()};
            TableModel.addRow(Linhas);
            
        }
            jTableUsuarios.setModel(TableModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddUsuario = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonAtualizarTabe = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 340));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuários:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jButtonAddUsuario.setText("ADD Usuário");
        jButtonAddUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUsuarioActionPerformed(evt);
            }
        });
        add(jButtonAddUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 100, -1));

        jButtonEditar.setText("Editar Usuário");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        jButtonAtualizarTabe.setText("Atualizar Tabela");
        jButtonAtualizarTabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarTabeActionPerformed(evt);
            }
        });
        add(jButtonAtualizarTabe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUsuarioActionPerformed
        // TODO add your handling code here:
        JFrame addUsuarios = new AddUsuarios();
        addUsuarios.setVisible(true);
    }//GEN-LAST:event_jButtonAddUsuarioActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        int linha = jTableUsuarios.getSelectedRow();
        if (linha != -1){
            Object idUsuario = jTableUsuarios.getValueAt(linha, 0);
            if(Integer.parseInt(idUsuario.toString())!= -1){
               AddUsuarios verProduto = new AddUsuarios(idUsuario.toString());
               verProduto.setVisible(true);
            }
        }else{
        JOptionPane.showMessageDialog(null, "Selecione a linha que deseja editar");}
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonAtualizarTabeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarTabeActionPerformed
        // TODO add your handling code here:
        //Aplicacao.Corpo.removeAll();
        Aplicacao.Corpo.revalidate();
        JPanel AtualizaNF = new lUsuarios();
        Aplicacao.Corpo.add(AtualizaNF, BorderLayout.CENTER);
        jTextField1.requestFocus();
    }//GEN-LAST:event_jButtonAtualizarTabeActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        SearchJTable.SearchJTable(jTableUsuarios, jTextField1);
    }//GEN-LAST:event_jTextField1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddUsuario;
    private javax.swing.JButton jButtonAtualizarTabe;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
